export const ActionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    DECRESE_QUANTITY: 'DECRESE_QUANTITY',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
    GET_NUMBER_IN_CART: 'GET_NUMBER_IN_CART',
}